# Generated by Django 5.1.3 on 2025-06-13 20:15

import builtins
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='fecha_fundacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=builtins.id),
        ),
    ]
