# Generated by Django 5.1.3 on 2025-06-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MisComunas', '0002_alter_comuna_fecha_fundacion_alter_comuna_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
